In [1]:
import pygmo as pg
import numpy as np
from problem import SignalProcessingParams

In [2]:
prob1 = pg.problem(SignalProcessingParams(group_number=1))
# prob2 = pg.problem(SignalProcessingParams(group_number=2))
print(prob1)
# print(prob2)

Problem name: Optimize EMG signal processing parameters to cross-corelate with grip force
	C++ class name: pybind11::object

	Global dimension:			251
	Integer dimension:			1
	Fitness dimension:			1
	Number of objectives:			1
	Equality constraints dimension:		0
	Inequality constraints dimension:	0
	Lower bounds: [0, 0, 0, 0, 0, ... ]
	Upper bounds: [2, 2, 2, 2, 2, ... ]
	Has batch fitness evaluation: false

	Has gradient: false
	User implemented gradient sparsity: false
	Has hessians: false
	User implemented hessians sparsity: false

	Fitness evaluations: 0

	Thread safety: none

Extra info:
	Sampling rate: 992.969696969697 Hz
	FFT window size: 496 samples
	FFT resolution: 2.0019550342130987 Hz



In [3]:
# Add parameter names using FFT frequencies
param_names = list(np.round(prob1.extract(SignalProcessingParams).emg_fft_freq[1:], decimals=2))
param_names = ['f' + str(i) for i in param_names] + ['decay', 'window']
param_names = [i.replace('.', '_') for i in param_names]
np.savetxt('param_names.txt', X=np.column_stack((
  np.arange(start=1, stop=len(param_names)+1), param_names
  )), fmt='%s')
# param_names

In [4]:
params_select = np.loadtxt('emg_dsample.txt', delimiter=' ')
# selected_params = ('f2_0', 'f446_44', 'decay', 'window')
# selected_index = [param_names.index(i) for i in selected_params]
# selected_index
# Always remove DC offset
# params = np.ones((params_select.shape[0], 250))
# params[:, selected_index] = params_select
params = params_select
params = np.column_stack((np.zeros(params.shape[0]), params))
params.shape

(1000, 251)

In [5]:
corr1 = [1 - prob1.fitness(i) for i in params]
# corr2 = [prob2.fitness(i) for i in params]

In [10]:
max(corr1)
corr2 = np.loadtxt('corr2.csv')
display(corr2[:10])
np.savetxt('corrs_dsample.txt', X=np.column_stack((corr1, corr2)), delimiter=' ')

[array([0.9109319]),
 array([0.92250355]),
 array([0.93836428]),
 array([0.92179429]),
 array([0.93270917]),
 array([0.93508853]),
 array([0.90001137]),
 array([0.92625694]),
 array([0.92983891]),
 array([0.93139162]),
 array([0.90648071]),
 array([0.91492076]),
 array([0.91202074]),
 array([0.92059935]),
 array([0.90180833]),
 array([0.93330652]),
 array([0.9082196]),
 array([0.92322342]),
 array([0.9403042]),
 array([0.93254957]),
 array([0.93553375]),
 array([0.92071284]),
 array([0.93437952]),
 array([0.93650367]),
 array([0.93051918]),
 array([0.92596028]),
 array([0.92639378]),
 array([0.93376277]),
 array([0.90509664]),
 array([0.90770245]),
 array([0.92938821]),
 array([0.94070225]),
 array([0.94622644]),
 array([0.9120342]),
 array([0.92960035]),
 array([0.91672912]),
 array([0.94227012]),
 array([0.92247992]),
 array([0.93266426]),
 array([0.92747302]),
 array([0.93871568]),
 array([0.90530852]),
 array([0.93736459]),
 array([0.93671676]),
 array([0.93346057]),
 array([0.9346

In [ ]:
# Slicing only first 100 corrs and params
np.savetxt('emg_dsample_100.txt', X=params[:100, 1:], delimiter=' ')
np.savetxt('corrs_dsample_100.txt', X=np.column_stack((corr1, corr2))[:100, :], delimiter=' ')

In [ ]:
%%timeit -n1 -r1
pop1 = pg.population(prob, size=20)

In [ ]:
3300 / 3600

In [ ]:
print(pop1)

In [ ]:
pop1.get_x()[32][-1]

In [ ]:
pop1.champion_x